apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-orchestrator
  namespace: sse-ai
  labels:
  {{- include "ai-orch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: ai-orchestrator
  template:
    metadata:
      creationTimestamp: null
      labels:
      {{- include "ai-orch.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
      serviceAccountName: pat-service-account
      automountServiceAccountToken: true
      containers:
        - name: ai-orchestrator
          image: {{ .Values.app.image.name }}
          imagePullPolicy: Always  # Example of specifying image pull policy
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: {{ .Values.app.ports.containerPort}}
              protocol: {{ .Values.app.ports.protocol}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          env:
            {{- toYaml .Values.app.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}