apiVersion: v1
kind: Service
metadata:
  name: ai-orchestrator-service
  namespace: sse-ai
  labels:
  {{- include "ai-orch.labels" . | nindent 8 }}
spec:
  selector:
    env: dev
    app: ai-orchestrator
    app.kubernetes.io/instance: ai-orchestrator
    app.kubernetes.io/name: ai-orchestrator
    project: datascience
    user: ci
  type: {{ .Values.service.type }}  
  ports:
    - protocol: {{ .Values.service.protocol}}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  